### PR TITLE
add software version and feature list to marker tooltip

### PR DESCRIPTION
**Pull request by jks-prv**

### CODE REVIEW

**Comment by linkfanel** [comment]
Can you clarify what intended use cases you have in mind exactly? I don't think that the version number is information that's really relevant to the average user, and I'd like to avoid clutter. Individual features might be better served by separate parsing and representation for each useful one.

On the other hand, it could indeed be interesting to display that line as is just for the sake of familiarity, as it is a main piece of information displayed on http://kiwisdr.com/public/

**Comment by jks-prv** [comment]
An alternative that’s even more useful would be to provide a search box that would filter the markers shown. E.g. if you were interested only in 20 kHz Kiwis, DRM-capable or, in my case, Kiwis running a particular release.

I’ve been meaning to add a search function to kiwisdr.com/public as this is the one feature still causing me to use sdr.hu. After a release I use it to check if Kiwis are successfully updating or not.

**Comment by linkfanel** [comment]
I've pushed an equivalent feature, thanks for the suggestion.

**Comment by jks-prv** [comment]
Thank you. Very useful for me and I'm sure for others as well. Appreciate your efforts.

**Pull request closed without merging**
